openapi: 3.0.3
info:
  title: Subscriber Service
  description: Subscriber service allowing subscriptions to newsletters and post sending.
  version: 0.0.0
servers:
  - url: http://localhost
    description: Localhost server running on HTTP.

paths:
  "/ping":
    get:
      description: Health check
      operationId: Ping
      summary: Check the healthiness of the service
      responses:
        "204":
          description: Service is operational
        "400":
          description: Invalid request
          
  "/subscriptions/subscribe":
    post:
      summary: Subscribe to a newsletter
      operationId: SubscribeToNewsletter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscribeRequest"
      responses:
        "200":
          description: Subscription successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
        "400":
          description: Invalid input

  "/subscriptions/confirm":
    get:
      summary: Confirm a subscription
      operationId: ConfirmSubscription
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Subscription confirmed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"
        "400":
          description: Invalid token

  "/subscriptions/unsubscribe":
    get:
      summary: Unsubscribe from a newsletter
      operationId: UnsubscribeFromNewsletter
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Unsubscribed successfully
        "400":
          description: Invalid input

  "/internal/publish-post":
    post:
      summary: Send published post to subscribers (internal)
      operationId: SendPublishedPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "200":
          description: Post delivered to subscribers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Invalid request body or validation error
        "500":
          description: Internal server error


  "/internal/delete-newsletter":
    delete:
      summary: delete newsletter subscriptions available internally
      operationId: DeleteNewsletterSubscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: The newsletter ID as a JSON string, e.g. "02ce2891-1461-4b91-bb7b-35de941d5cdd"
      responses:
        "204":
          description: Subscriptions deleted
        "400":
          description: Invalid request
        "500":
          description: Internal server error

components:
  schemas:
    SubscribeRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        newsletter_id:
          type: string
      required:
        - email
        - newsletter_id
    Subscription:
      type: object
      properties:
        id:
          type: string
        newsletter_id:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - newsletter_id
        - email
        - created_at
    Post:
      type: object
      properties:
        newsletter_id:
          type: string
        title:
          type: string
        content:
          type: string
      required:
        - newsletter_id
        - title
        - content