services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - editor-service
      - newsletter-service
      - subscriber-service
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  postgres_editor:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: editordatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_editor_data:/var/lib/postgresql/data

  postgres_newsletter:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletterdatabase
    expose:
      - "5432:5433"
    volumes:
      - postgres_newsletter_data:/var/lib/postgresql/data

  editor-service:
    build:
      context: ./editor-service
      dockerfile: Dockerfile
    ports:
      - "8081"
    environment:
      PORT: 8081
      DATABASE_URL: postgres://user:password@postgres_editor:5432/editordatabase
      FIREBASE_CRED: "/app/firebase-admin-sdk.json"
    env_file:
      - editor-service/.env

  newsletter-service:
    build:
      context: ./newsletter-service
      dockerfile: Dockerfile
    ports:
      - "8082"
    environment:
      PORT: 8082
      DATABASE_URL: postgres://user:password@postgres_newsletter:5432/newsletterdatabase?sslmode=disable
      SERVICE_TOKEN: ## openssl rand -base64 32 - has the be the same as the subscriber's service
      
  
  subscriber-service:
    build:
      context: ./subscriber-service
      dockerfile: Dockerfile
    expose:
      - "8083"
    environment:
      PORT: 8083
      SERVICE_ACCOUNT: "/app/firebase-admin-sdk.json"
      EMAIL_ADDRESS: "newsletter_email_address"
      RESEND_API_KEY: "re_37p9fSD2_FCSyR7zNE7utrW9jcs2sNcbA"
      BASE_URL: "http://localhost:8080"
      NEWSLETTER_JWT_SECRET: ## openssl rand -base64 32
      SERVICE_TOKEN: ## openssl rand -base64 32 - has to be the same as the newsletter's service

  migrate-editor:
    image: migrate/migrate
    volumes:
      - ./editor-service/repository/sql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@postgres_editor:5432/editordatabase?sslmode=disable",
      "-verbose",
      "up"
    ]
    depends_on:
      - postgres_editor

  migrate-newsletter:
    image: migrate/migrate
    volumes:
      - ./newsletter-service/repository/sql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@postgres_newsletter:5432/newsletterdatabase?sslmode=disable",
      "-verbose",
      "up"
    ]
    depends_on:
      - postgres_newsletter

volumes:
  postgres_editor_data:
  postgres_newsletter_data:
