services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - editor-service
      - newsletter-service
      - subscriber-service
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  postgres_editor:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: editordatabase
    expose:
      - "5432:5432"
    volumes:
      - postgres_editor_data:/var/lib/postgresql/data

  postgres_newsletter:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletterdatabase
    expose:
      - "5432:5433"
    volumes:
      - postgres_newsletter_data:/var/lib/postgresql/data

  editor-service:
    build:
      context: ./editor-service
      dockerfile: Dockerfile
    expose:
      - "8081"
    depends_on:
      - postgres_editor
    environment:
      PORT: 8081
      DATABASE_URL: postgres://user:password@postgres_editor:5432/editordatabase
      FIREBASE_CRED: "/app/firebase-admin-sdk.json"

  newsletter-service:
    build:
      context: ./newsletter-service
      dockerfile: Dockerfile
    expose:
      - "8082"
    depends_on:
      - postgres_newsletter
    environment:
      PORT: 8082
      DATABASE_URL: postgres://user:password@postgres_newsletter:5432/newsletterdatabase?sslmode=disable
  
  subscriber-service:
    build:
      context: ./subscriber-service
      dockerfile: Dockerfile
    expose:
      - "8083"
    environment:
      PORT: 8083
      SERVICE_ACCOUNT: "/app/firebase-admin-sdk.json"
      EMAIL_ADDRESS: ""
      BASE_URL: "http://localhost:8080"

  migrate:
    image: migrate/migrate
    volumes:
      - ./editor-service/repository/sql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@postgres_editor:5432/editordatabase?sslmode=disable",
      "-verbose",
      "up"
    ]
    depends_on:
      - postgres_editor
      - postgres_newsletter

volumes:
  postgres_editor_data:
  postgres_newsletter_data:
