services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - editor-service
      - newsletter-service
      - subscriber-service
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  postgres_editor:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: editordatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_editor_data:/var/lib/postgresql/data

  postgres_newsletter:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletterdatabase
    expose:
      - "5433:5432"
    volumes:
      - postgres_newsletter_data:/var/lib/postgresql/data

  editor-service:
    build:
      context: ./editor-service
      dockerfile: Dockerfile
    ports:
      - "8081"
    env_file:
      - ./editor-service/.env

  newsletter-service:
    build:
      context: ./newsletter-service
      dockerfile: Dockerfile
    ports:
      - "8082"
    env_file:
      - ./editor-service/.env
    environment:
      PORT: 8082
      DATABASE_URL: postgres://user:password@postgres_newsletter:5432/newsletterdatabase
      SERVICE_TOKEN: "uhQq9NNRO6eK0bHykgfc6jNQ5piumqO0nRvA8cxqw1U="
      FIREBASE_CRED: /app/firebase-admin-sdk.json
      FIREBASE_PROJECT_ID: goproject-4c949
      AUTH_SECRET: /app/firebase-admin-sdk.json
    volumes:
      - ./newsletter-service/firebase-admin-sdk.json:/app/firebase-admin-sdk.json:ro
  
  subscriber-service:
    build:
      context: ./subscriber-service
      dockerfile: Dockerfile
    expose:
      - "8083"
    env_file:
      - ./subscriber-service/.env
  migrate-editor:
    image: migrate/migrate
    volumes:
      - ./editor-service/repository/sql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@postgres_editor:5432/editordatabase?sslmode=disable",
      "-verbose",
      "up"
    ]
    depends_on:
      - postgres_editor

  migrate-newsletter:
    image: migrate/migrate
    volumes:
      - ./newsletter-service/repository/sql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@postgres_newsletter:5432/newsletterdatabase?sslmode=disable",
      "-verbose",
      "up"
    ]
    depends_on:
      - postgres_newsletter

volumes:
  postgres_editor_data:
  postgres_newsletter_data:
