openapi: 3.1.0
info:
  title: Editor Service API
  version: 1.0.0
  description: API pro správu editorů

servers:
  - url: http://localhost:8080

paths:
  /signup:
    post:
      summary: Registrace editora
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: Editor created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid input

  /signin:
    post:
      summary: Přihlášení editora
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
              required:
                - id_token
      responses:
        '200':
          description: Přihlášení úspěšné
        '401':
          description: Invalid ID token

  /change-password:
    post:
      summary: Změna hesla editora
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                old_password:
                  type: string
                new_password:
                  type: string
              required:
                - email
                - old_password
                - new_password
      responses:
        '200':
          description: Heslo změněno
        '400':
          description: Invalid input