openapi: 3.0.3
info:
  title: editor management service
  description: editor management service allowing to manage editors.
  version: 0.0.0
servers:
  - url: http://localhost
    description: Localhost server running on HTTP.

paths:
  "/ping":
    get:
      description: Health check
      operationId: Ping
      summary: Check the healthiness of the service
      responses:
        "204":
          description: It's ALIVE (a.k.a. service is up and running)
        "400":
          description: Invalid request
  "/editors":
    post:
      description: Create a new editor
      operationID: Createeditor
      summary: Create a new editor
      requestBody:
        description: editor information for editor creation
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/editor"
      responses:
        "201":
          description: editor created scuccessfully
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/editor"
        "400":
          description: Invalid request
    get:
      description: Get all editors
      operationId: Listeditor
      summary: List all editors
      responses:
        "200":
          description: A list of editors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/editor"
        "400":
          description: Invalid request
  "/editors/{email}":
    get:
      description: Get a editor
      operationId: Geteditor
      summary: Gets a specific editor by email
      parameters:
        - name: email
          in: path
          description: Email of the editor to get
          required: true
          schema:
            type: string
            format: email
      responses:
        "200":
          description: editor found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/editor"
        "404":
          description: editor not found
        "400":
          description: Invalid request
    put:
      description: Update a editor
      operationId: Updateeditor
      summary: Updates a specific editor by email
      parameters:
        - name: email
          in: path
          description: Email of the editor to get
          required: true
          schema:
            type: string
            format: email
      requestBody:
        description: editor information for editor creation
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/editor"
      responses:
        "200":
          description: editor updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/editor"
        "404":
          description: editor not found
        "400":
          description: Invalid request
    delete:
      description: Delete a editor
      operationId: Deleteeditor
      summary: Deletes a specific editor by email
      parameters:
        - name: email
          in: path
          description: Email of the editor to get
          required: true
          schema:
            type: string
            format: email
      responses:
        "204":
          description: editor deleted successfully
        "404":
          description: editor not found
        "400":
          description: Invalid request
components:
  schemas:
    editor:
      type: object
      properties:
        email:
          type: string
          format: email
        firstname:
          type: string
        lastname:
          type: string
      required:
        - email
        - firstname
        - lastname

